# Generated by Django 6.0.5 on 2026-08-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("short", "Short-form"),
                            ("commercial", "Commercial"),
                            ("wedding", "Wedding / Event"),
                            ("music", "Music Video"),
                            ("documentary", "Documentary"),
                            ("motion", "Motion Graphics"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=60,
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "video_url",
                    models.URLField(help_text="YouTube/Vimeo direct link or .mp4 URL."),
                ),
                ("thumbnail", models.ImageField(blank=True, upload_to="thumbnails/")),
                (
                    "cover_color",
                    models.CharField(
                        default="#f5a524",
                        help_text="Hex fallback colour behind the thumbnail.",
                        max_length=7,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["featured", "order"],
                        name="core_videop_feature_7c51bf_idx",
                    )
                ],
            },
        ),
    ]
