# Generated by Django 6.1 on 2026-08-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_switch_to_light_purple"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoproject",
            name="category",
            field=models.CharField(
                choices=[
                    ("music", "Music Video"),
                    ("visualizer", "Visualizer"),
                    ("cinematic", "Cinematic Edit"),
                    ("promo", "Artist Promo"),
                    ("lyric", "Lyric / Typography"),
                    ("atmospheric", "Atmospheric / Experimental"),
                    ("social", "Social Content"),
                    ("spiritual", "Artistic / Spiritual"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=60,
            ),
        ),
    ]
